name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-docker-build:
    name: Test and Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Show Go version
        run: go version

      - name: Run Go tests
        run: go test ./...

      - name: Build Docker image
        run: docker build -t devops-local-pipeline-lab:${{ github.sha }} .

      - name: Scan Docker image with Trivy
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --exit-code 0 \
            --ignore-unfixed \
            --severity HIGH,CRITICAL \
            devops-local-pipeline-lab:${{ github.sha }}

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm chart
        run: helm lint charts/microservice

      - name: Render Helm templates
        run: helm template devops-local-pipeline-lab charts/microservice
